-- Deployment template: review and replace every <...> before execution.
-- Use a STANDARD database and permanent managed-access schemas for ledgers.
-- Do not use APP/private storage schemas or existing business-data schemas.
-- This template has not been validated in App Runtime or on Hybrid Tables.

-- Schema owner/deployment administrator (SYSADMIN or its subordinate role).
CREATE SCHEMA <LEDGER_DB>.<DEPARTMENT_DATA_SCHEMA> WITH MANAGED ACCESS;
CREATE SCHEMA <LEDGER_DB>.<DEPARTMENT_DEFINITION_SCHEMA> WITH MANAGED ACCESS;

-- SECURITYADMIN (or an administrator authorized to manage these roles/grants).
CREATE ROLE <DEPARTMENT_LEDGER_READER>;
CREATE ROLE <DEPARTMENT_LEDGER_WRITER>;
GRANT ROLE <DEPARTMENT_LEDGER_READER> TO ROLE <DEPARTMENT_LEDGER_WRITER>;
GRANT ROLE <DEPARTMENT_LEDGER_WRITER> TO ROLE SYSADMIN;
GRANT USAGE ON DATABASE <LEDGER_DB> TO ROLE <DEPARTMENT_LEDGER_READER>;
GRANT USAGE ON SCHEMA <LEDGER_DB>.<DEPARTMENT_DATA_SCHEMA> TO ROLE <DEPARTMENT_LEDGER_READER>;
GRANT USAGE ON SCHEMA <LEDGER_DB>.<DEPARTMENT_DEFINITION_SCHEMA> TO ROLE <DEPARTMENT_LEDGER_READER>;
GRANT USAGE ON WAREHOUSE <QUERY_WAREHOUSE> TO ROLE <DEPARTMENT_LEDGER_READER>;

-- Give READER to the department's viewing job role, WRITER to its input job role.
-- No per-user role is needed. Do not grant WRITER to a viewing-only job role.
-- GRANT ROLE <DEPARTMENT_LEDGER_READER> TO ROLE <VIEWING_JOB_ROLE>;
-- GRANT ROLE <DEPARTMENT_LEDGER_WRITER> TO ROLE <INPUT_JOB_ROLE>;

-- Schema owner: current and future grants are both needed.
-- TABLE/TABLES covers standard AND hybrid tables.
GRANT SELECT ON ALL TABLES IN SCHEMA <LEDGER_DB>.<DEPARTMENT_DATA_SCHEMA> TO ROLE <DEPARTMENT_LEDGER_READER>;
GRANT SELECT ON FUTURE TABLES IN SCHEMA <LEDGER_DB>.<DEPARTMENT_DATA_SCHEMA> TO ROLE <DEPARTMENT_LEDGER_READER>;
GRANT SELECT ON ALL TABLES IN SCHEMA <LEDGER_DB>.<DEPARTMENT_DEFINITION_SCHEMA> TO ROLE <DEPARTMENT_LEDGER_READER>;
GRANT SELECT ON FUTURE TABLES IN SCHEMA <LEDGER_DB>.<DEPARTMENT_DEFINITION_SCHEMA> TO ROLE <DEPARTMENT_LEDGER_READER>;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA <LEDGER_DB>.<DEPARTMENT_DATA_SCHEMA> TO ROLE <DEPARTMENT_LEDGER_WRITER>;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA <LEDGER_DB>.<DEPARTMENT_DATA_SCHEMA> TO ROLE <DEPARTMENT_LEDGER_WRITER>;
GRANT UPDATE ON ALL TABLES IN SCHEMA <LEDGER_DB>.<DEPARTMENT_DEFINITION_SCHEMA> TO ROLE <DEPARTMENT_LEDGER_WRITER>;
GRANT UPDATE ON FUTURE TABLES IN SCHEMA <LEDGER_DB>.<DEPARTMENT_DEFINITION_SCHEMA> TO ROLE <DEPARTMENT_LEDGER_WRITER>;

-- Default storage="hybrid": grant its separate creation privilege on BOTH schemas.
GRANT CREATE HYBRID TABLE ON SCHEMA <LEDGER_DB>.<DEPARTMENT_DATA_SCHEMA> TO ROLE <DEPARTMENT_LEDGER_WRITER>;
GRANT CREATE HYBRID TABLE ON SCHEMA <LEDGER_DB>.<DEPARTMENT_DEFINITION_SCHEMA> TO ROLE <DEPARTMENT_LEDGER_WRITER>;
-- For storage="standard", replace the preceding two statements with:
-- GRANT CREATE TABLE ON SCHEMA <LEDGER_DB>.<DEPARTMENT_DATA_SCHEMA> TO ROLE <DEPARTMENT_LEDGER_WRITER>;
-- GRANT CREATE TABLE ON SCHEMA <LEDGER_DB>.<DEPARTMENT_DEFINITION_SCHEMA> TO ROLE <DEPARTMENT_LEDGER_WRITER>;

-- Restrict the Runtime service owner's CALLER grants to these approved schemas.
-- These are ceilings on user privileges, not ordinary grants to the service owner.
-- Use a grant administrator with MANAGE CALLER GRANTS and access to these objects.
GRANT CALLER USAGE ON DATABASE <LEDGER_DB> TO ROLE <SERVICE_OWNER_ROLE>;
GRANT CALLER USAGE ON SCHEMA <LEDGER_DB>.<DEPARTMENT_DATA_SCHEMA> TO ROLE <SERVICE_OWNER_ROLE>;
GRANT CALLER USAGE ON SCHEMA <LEDGER_DB>.<DEPARTMENT_DEFINITION_SCHEMA> TO ROLE <SERVICE_OWNER_ROLE>;
GRANT CALLER USAGE ON WAREHOUSE <QUERY_WAREHOUSE> TO ROLE <SERVICE_OWNER_ROLE>;
GRANT INHERITED CALLER SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA <LEDGER_DB>.<DEPARTMENT_DATA_SCHEMA> TO ROLE <SERVICE_OWNER_ROLE>;
-- INSERT is used only to initialize the caller-created definition table.
GRANT INHERITED CALLER SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA <LEDGER_DB>.<DEPARTMENT_DEFINITION_SCHEMA> TO ROLE <SERVICE_OWNER_ROLE>;
-- Permit cleanup only when the caller actually owns a table in these schemas.
-- OWNERSHIP caller grants do not grant ownership to the service owner or users.
GRANT INHERITED CALLER OWNERSHIP ON ALL TABLES IN SCHEMA <LEDGER_DB>.<DEPARTMENT_DATA_SCHEMA> TO ROLE <SERVICE_OWNER_ROLE>;
GRANT INHERITED CALLER OWNERSHIP ON ALL TABLES IN SCHEMA <LEDGER_DB>.<DEPARTMENT_DEFINITION_SCHEMA> TO ROLE <SERVICE_OWNER_ROLE>;
GRANT CALLER CREATE HYBRID TABLE ON SCHEMA <LEDGER_DB>.<DEPARTMENT_DATA_SCHEMA> TO ROLE <SERVICE_OWNER_ROLE>;
GRANT CALLER CREATE HYBRID TABLE ON SCHEMA <LEDGER_DB>.<DEPARTMENT_DEFINITION_SCHEMA> TO ROLE <SERVICE_OWNER_ROLE>;
-- For storage="standard", replace the preceding two statements with:
-- GRANT CALLER CREATE TABLE ON SCHEMA <LEDGER_DB>.<DEPARTMENT_DATA_SCHEMA> TO ROLE <SERVICE_OWNER_ROLE>;
-- GRANT CALLER CREATE TABLE ON SCHEMA <LEDGER_DB>.<DEPARTMENT_DEFINITION_SCHEMA> TO ROLE <SERVICE_OWNER_ROLE>;

-- If grant revocation must affect a role that created a ledger, transfer table
-- OWNERSHIP to the department schema administrator using COPY CURRENT GRANTS.
-- Creators otherwise retain OWNERSHIP; revoking UPDATE alone cannot remove it.
-- Do not transfer ownership while a ledger is being provisioned. Review cleanup
-- rights and recover any incomplete tables reported by the app administrator.
-- Never grant these roles or ordinary ledger SELECT to private/Dataset storage
-- procedure owners. Exploration still has no business-source write privileges.
