-- Run with an administrator role in the chosen app database.
-- Change database and roles to your installation; do not grant blanket access.
CREATE DATABASE IF NOT EXISTS SNOWFLAKE_APPS;
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_APPS.APP;
CREATE TABLE IF NOT EXISTS SNOWFLAKE_APPS.APP.METADATA (
  OWNER VARCHAR NOT NULL,
  KIND VARCHAR NOT NULL,
  ID VARCHAR NOT NULL,
  PAYLOAD VARIANT NOT NULL,
  UPDATED_AT TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS SNOWFLAKE_APPS.APP.DATASETS LIKE SNOWFLAKE_APPS.APP.METADATA;
CREATE ROW ACCESS POLICY IF NOT EXISTS SNOWFLAKE_APPS.APP.METADATA_VISIBILITY
AS (ROW_OWNER VARCHAR, ROW_KIND VARCHAR) RETURNS BOOLEAN ->
  ROW_OWNER = CURRENT_USER();
ALTER TABLE SNOWFLAKE_APPS.APP.METADATA ADD ROW ACCESS POLICY
  SNOWFLAKE_APPS.APP.METADATA_VISIBILITY ON (OWNER, KIND);
-- The ALTER above is one-time; omit it on subsequent setup runs.
-- Separate roles: app deployer / ordinary explorer / Dataset Owner.
-- Replace placeholders before executing the examples below.
-- GRANT USAGE ON DATABASE SNOWFLAKE_APPS TO ROLE <EXPLORER_ROLE>;
-- GRANT USAGE ON SCHEMA SNOWFLAKE_APPS.APP TO ROLE <EXPLORER_ROLE>;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE SNOWFLAKE_APPS.APP.METADATA TO ROLE <EXPLORER_ROLE>;
-- GRANT SELECT ON TABLE SNOWFLAKE_APPS.APP.DATASETS TO ROLE <EXPLORER_ROLE>;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE SNOWFLAKE_APPS.APP.DATASETS TO ROLE <DATASET_OWNER_ROLE>;
-- Metadata mutations execute as caller. Dataset publishing requires INSERT/UPDATE.
-- GRANT CALLER USAGE ON DATABASE SNOWFLAKE_APPS TO ROLE <SERVICE_OWNER_ROLE>;
-- GRANT CALLER USAGE ON SCHEMA SNOWFLAKE_APPS.APP TO ROLE <SERVICE_OWNER_ROLE>;
-- GRANT CALLER SELECT, INSERT, UPDATE, DELETE ON TABLE SNOWFLAKE_APPS.APP.METADATA TO ROLE <SERVICE_OWNER_ROLE>;
-- GRANT CALLER SELECT, INSERT, UPDATE, DELETE ON TABLE SNOWFLAKE_APPS.APP.DATASETS TO ROLE <SERVICE_OWNER_ROLE>;
-- GRANT CALLER USAGE ON DATABASE <DATA_DB> TO ROLE <SERVICE_OWNER_ROLE>;
-- GRANT CALLER USAGE ON SCHEMA <DATA_DB>.<DATA_SCHEMA> TO ROLE <SERVICE_OWNER_ROLE>;
-- GRANT CALLER SELECT ON ALL TABLES IN SCHEMA <DATA_DB>.<DATA_SCHEMA> TO ROLE <SERVICE_OWNER_ROLE>;
-- Add equivalent caller grants for views, dynamic tables and semantic views you expose.
