-- Run with an administrator role in the chosen app database.
-- Change database and roles to your installation; do not grant blanket access.
CREATE DATABASE IF NOT EXISTS SNOWFLAKE_APPS;
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_APPS.APP;
-- PRINCIPALS is administered through the identity lifecycle, not through the app.
CREATE TABLE IF NOT EXISTS SNOWFLAKE_APPS.APP.PRINCIPALS (
  SNOWFLAKE_USERNAME VARCHAR NOT NULL,
  PRINCIPAL_ID VARCHAR NOT NULL,
  ENABLED BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE OR REPLACE SECURE FUNCTION SNOWFLAKE_APPS.APP.CURRENT_PRINCIPAL()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
  SELECT CASE WHEN COUNT(*)=1 THEN MAX(PRINCIPAL_ID) ELSE NULL END
  FROM SNOWFLAKE_APPS.APP.PRINCIPALS
  WHERE SNOWFLAKE_USERNAME=CURRENT_USER() AND ENABLED=TRUE
    AND LENGTH(PRINCIPAL_ID) BETWEEN 1 AND 200
    AND LENGTH(TRIM(PRINCIPAL_ID))>0
    AND PRINCIPAL_ID IN (
      SELECT PRINCIPAL_ID FROM SNOWFLAKE_APPS.APP.PRINCIPALS
      WHERE ENABLED=TRUE GROUP BY PRINCIPAL_ID HAVING COUNT(*)=1
    )
$$;
-- Identity admin registers each user with an immutable IdP/SCIM ID or fresh UUID.
-- INSERT INTO SNOWFLAKE_APPS.APP.PRINCIPALS VALUES ('USER_A', '<immutable-user-a-id>', TRUE);
-- Rename keeps the principal ID; deletion disables this binding before name reuse.
CREATE TABLE IF NOT EXISTS SNOWFLAKE_APPS.APP.METADATA (
  OWNER VARCHAR NOT NULL,
  KIND VARCHAR NOT NULL,
  ID VARCHAR NOT NULL,
  PAYLOAD VARIANT NOT NULL,
  UPDATED_AT TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS SNOWFLAKE_APPS.APP.DATASETS LIKE SNOWFLAKE_APPS.APP.METADATA;
CREATE TABLE IF NOT EXISTS SNOWFLAKE_APPS.APP.PERSONAL_TABLES LIKE SNOWFLAKE_APPS.APP.METADATA;
CREATE ROW ACCESS POLICY IF NOT EXISTS SNOWFLAKE_APPS.APP.PRIVATE_VISIBILITY
AS (ROW_OWNER VARCHAR, ROW_KIND VARCHAR) RETURNS BOOLEAN ->
  ROW_OWNER = SNOWFLAKE_APPS.APP.CURRENT_PRINCIPAL();
ALTER TABLE SNOWFLAKE_APPS.APP.METADATA ADD ROW ACCESS POLICY
  SNOWFLAKE_APPS.APP.PRIVATE_VISIBILITY ON (OWNER, KIND);
ALTER TABLE SNOWFLAKE_APPS.APP.PERSONAL_TABLES ADD ROW ACCESS POLICY
  SNOWFLAKE_APPS.APP.PRIVATE_VISIBILITY ON (OWNER, KIND);
-- The ALTER statements above are one-time; omit it on subsequent setup runs.
-- Separate roles: app deployer / ordinary explorer / Dataset Owner.
-- Replace placeholders before executing the examples below.
-- GRANT USAGE ON DATABASE SNOWFLAKE_APPS TO ROLE <EXPLORER_ROLE>;
-- GRANT USAGE ON SCHEMA SNOWFLAKE_APPS.APP TO ROLE <EXPLORER_ROLE>;
-- GRANT SELECT ON TABLE SNOWFLAKE_APPS.APP.METADATA TO ROLE <EXPLORER_ROLE>;
-- GRANT SELECT ON TABLE SNOWFLAKE_APPS.APP.PERSONAL_TABLES TO ROLE <EXPLORER_ROLE>;
-- GRANT SELECT ON TABLE SNOWFLAKE_APPS.APP.DATASETS TO ROLE <EXPLORER_ROLE>;
-- Shared writes use sql/dataset-state.sql with Dataset editor procedure USAGE only.
-- Private writes use sql/private-state.sql; RAP alone does not restrict inserts.
-- Both procedures write definitions only; business queries always use caller rights.
-- GRANT CALLER USAGE ON DATABASE SNOWFLAKE_APPS TO ROLE <SERVICE_OWNER_ROLE>;
-- GRANT CALLER USAGE ON SCHEMA SNOWFLAKE_APPS.APP TO ROLE <SERVICE_OWNER_ROLE>;
-- GRANT CALLER SELECT ON TABLE SNOWFLAKE_APPS.APP.METADATA TO ROLE <SERVICE_OWNER_ROLE>;
-- GRANT CALLER SELECT ON TABLE SNOWFLAKE_APPS.APP.PERSONAL_TABLES TO ROLE <SERVICE_OWNER_ROLE>;
-- GRANT CALLER SELECT ON TABLE SNOWFLAKE_APPS.APP.DATASETS TO ROLE <SERVICE_OWNER_ROLE>;
-- GRANT USAGE ON FUNCTION SNOWFLAKE_APPS.APP.CURRENT_PRINCIPAL() TO ROLE <EXPLORER_ROLE>;
-- GRANT CALLER USAGE ON FUNCTION SNOWFLAKE_APPS.APP.CURRENT_PRINCIPAL() TO ROLE <SERVICE_OWNER_ROLE>;
-- GRANT CALLER USAGE ON DATABASE <DATA_DB> TO ROLE <SERVICE_OWNER_ROLE>;
-- GRANT CALLER USAGE ON SCHEMA <DATA_DB>.<DATA_SCHEMA> TO ROLE <SERVICE_OWNER_ROLE>;
-- GRANT CALLER SELECT ON ALL TABLES IN SCHEMA <DATA_DB>.<DATA_SCHEMA> TO ROLE <SERVICE_OWNER_ROLE>;
-- Add equivalent caller grants for views, dynamic tables and semantic views you expose.

-- Function owner gets only identity-map SELECT and database/schema USAGE.
-- GRANT SELECT ON TABLE SNOWFLAKE_APPS.APP.PRINCIPALS TO ROLE <PRIVATE_STORAGE_OWNER_ROLE>;
-- GRANT OWNERSHIP ON FUNCTION SNOWFLAKE_APPS.APP.CURRENT_PRINCIPAL()
--   TO ROLE <PRIVATE_STORAGE_OWNER_ROLE> COPY CURRENT GRANTS;
-- App roles must not receive PRINCIPALS table privileges or either storage-owner role.
-- Existing name-based OWNER installations need an offline reviewed migration;
-- do not silently retain the old policy or fall back to CURRENT_USER ownership.
